title: "Hello. I'm AppCabin."
email: 'contact@appcabin.io'
description: "Distribution made simple."
baseurl: "" 
url: "https://appcabin.github.io"
twitter_username: 'appcabin'
github_username: 'appcabin'
medium_username: 'contact@appcabin.io'

# Build settings
markdown: kramdown
############################################################

### Phantom settings
footer_text: '© 2023 AppCabin'
admin_name: 'AppCabin'
google_analytics: "G-8NDK57C00T" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: false
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }

sections:
  - { 
    title: 'OTA (Over-The-Air) updates',
    position: 'left',
    lead_text: 'OTA updates for your React Native, Electron and MAUI apps',
    featured_image: '/img/posts/ota.png',
    tags: ["React Native", "Electron", "Flutter", "MAUI"]
  }
  - { 
    title: 'App Stores Distribution',
    position: 'right',
    lead_text: 'Distribute your applications to App Store, Google Play, Windows Store from one place',
    featured_image: '/img/posts/store.png',
    tags: ["AppStore", "Google Play", "Windows Store", "Amazon AppStore"]
  }
  - { 
    title: 'Plugin distribution',
    position: 'left',
    lead_text: 'Distribute your plugins for different products',
    featured_image: '/img/posts/plugins.png',
    tags: ["ChatGPT", "Visual Studio Marketplace", "NPM", "Nuget", "Maven"]
  }
  - { 
    title: 'Gradual rollouts',
    position: 'right',
    lead_text: 'Control the distirbution via gradial rollouts to testers and users',
    featured_image: '/img/posts/rollout.png',
    tags: ["Feature Flag", "Rollout", "Experimentation"]
  }      